#!/bin/bash

# Railway Environment Variables Setup Script for n8n
# This script helps you set all required environment variables in Railway

echo "=================================================="
echo "n8n Railway Environment Variables Setup"
echo "=================================================="
echo ""
echo "Copy and paste these commands in your terminal:"
echo "(Make sure you have Railway CLI installed and are logged in)"
echo ""
echo "# Core Configuration"
echo "railway variables set NODE_ENV=production"
echo "railway variables set N8N_PORT=\$PORT"
echo "railway variables set N8N_PROTOCOL=https"
echo "railway variables set N8N_HOST=0.0.0.0"
echo ""
echo "# URLs (Railway will auto-populate RAILWAY_PUBLIC_DOMAIN)"
echo "railway variables set WEBHOOK_URL=https://\$RAILWAY_PUBLIC_DOMAIN"
echo "railway variables set N8N_EDITOR_BASE_URL=https://\$RAILWAY_PUBLIC_DOMAIN"
echo ""
echo "# Security"
echo "railway variables set N8N_INSECURE_FRONTEND_ALLOWLIST=false"
echo ""
echo "# Executions"
echo "railway variables set EXECUTIONS_PROCESS=main"
echo "railway variables set EXECUTIONS_MODE=regular"
echo "railway variables set EXECUTIONS_TIMEOUT=3600"
echo "railway variables set EXECUTIONS_TIMEOUT_MAX=7200"
echo ""
echo "# Timezone"
echo "railway variables set GENERIC_TIMEZONE=UTC"
echo ""
echo "# Metrics & Monitoring (REQUIRED for /healthz endpoint)"
echo "railway variables set N8N_METRICS=true"
echo "railway variables set N8N_METRICS_INCLUDE_API_ENDPOINTS=true"
echo "railway variables set N8N_METRICS_INCLUDE_DEFAULT_METRICS=true"
echo "railway variables set N8N_METRICS_INCLUDE_WORKFLOW_ID_LABEL=true"
echo "railway variables set N8N_METRICS_INCLUDE_NODE_TYPE_LABEL=true"
echo "railway variables set N8N_DIAGNOSTICS_ENABLED=true"
echo ""
echo "# Logging"
echo "railway variables set N8N_LOG_LEVEL=info"
echo "railway variables set N8N_LOG_OUTPUT=console"
echo ""
echo "# Database (PostgreSQL - Railway will auto-populate PG* variables)"
echo "railway variables set DB_TYPE=postgresdb"
echo "railway variables set DB_POSTGRESDB_HOST=\$PGHOST"
echo "railway variables set DB_POSTGRESDB_PORT=\$PGPORT"
echo "railway variables set DB_POSTGRESDB_DATABASE=\$PGDATABASE"
echo "railway variables set DB_POSTGRESDB_USER=\$PGUSER"
echo "railway variables set DB_POSTGRESDB_PASSWORD=\$PGPASSWORD"
echo "railway variables set DB_POSTGRESDB_SCHEMA=public"
echo ""
echo "# User Management"
echo "railway variables set N8N_USER_MANAGEMENT_DISABLED=false"
echo ""
echo "# API & Features"
echo "railway variables set N8N_PUBLIC_API_DISABLED=false"
echo "railway variables set N8N_COMMUNITY_NODES_ENABLED=true"
echo "railway variables set N8N_PAYLOAD_SIZE_MAX=16"
echo ""
echo "=================================================="
echo ""
echo "IMPORTANT: Make sure you have:"
echo "1. PostgreSQL service added to your Railway project"
echo "2. Railway CLI installed: npm i -g @railway/cli"
echo "3. Logged in: railway login"
echo "4. Linked to your project: railway link"
echo ""
echo "=================================================="
